FROM python:3.13

WORKDIR /app
ENV PYTHONPATH="/app:$PYTHONPATH"

COPY ./data/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the inflow module
COPY ./data/inflow ./src/data/inflow
# Copy the mq module
COPY ./data/mq ./src/data/mq
# Copy the script
COPY ./scripts/run_inflow.py ./src/scripts/run_inflow.py

RUN touch ./src/__init__.py ./src/data/__init__.py ./src/scripts/__init__.py

CMD ["python", "-m", "src.scripts.run_inflow"]